version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_django_app:/my_django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/mysite
    depends_on:
      - web
